2018-05-07T09:35:19.750+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=b6f094b66809
2018-05-07T09:35:19.751+0000 I CONTROL  [initandlisten] db version v3.4.13
2018-05-07T09:35:19.751+0000 I CONTROL  [initandlisten] git version: fbdef2ccc53e0fcc9afb570063633d992b2aae42
2018-05-07T09:35:19.751+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2018-05-07T09:35:19.751+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-05-07T09:35:19.752+0000 I CONTROL  [initandlisten] modules: none
2018-05-07T09:35:19.752+0000 I CONTROL  [initandlisten] build environment:
2018-05-07T09:35:19.752+0000 I CONTROL  [initandlisten]     distmod: debian81
2018-05-07T09:35:19.752+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-05-07T09:35:19.753+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-05-07T09:35:19.753+0000 I CONTROL  [initandlisten] options: { security: { authorization: "enabled" }, systemLog: { destination: "file", path: "/logs/mongodb.log" } }
2018-05-07T09:35:19.754+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2018-05-07T09:35:19.760+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-05-07T09:35:19.787+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2018-05-07T09:35:19.788+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
2018-05-07T09:35:20.384+0000 I STORAGE  [initandlisten] WiredTiger message [1525685720:384400][8:0x7ffff7feed40], txn-recover: Main recovery loop: starting at 10/128
2018-05-07T09:35:20.405+0000 I STORAGE  [initandlisten] WiredTiger message [1525685720:405596][8:0x7ffff7feed40], txn-recover: Recovering log 10 through 11
2018-05-07T09:35:20.682+0000 I STORAGE  [initandlisten] WiredTiger message [1525685720:682937][8:0x7ffff7feed40], file:index-1--8279824087185450262.wt, txn-recover: Recovering log 11 through 11
2018-05-07T09:35:20.778+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2018-05-07T09:35:20.778+0000 I CONTROL  [initandlisten] 
2018-05-07T09:35:20.785+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-05-07T09:35:20.786+0000 I NETWORK  [thread1] waiting for connections on port 27017
2018-05-07T09:35:23.144+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58478 #1 (1 connection now open)
2018-05-07T09:35:23.146+0000 I NETWORK  [conn1] received client metadata from 172.18.1.1:58478 conn1: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:35:23.198+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58480 #2 (2 connections now open)
2018-05-07T09:35:23.200+0000 I NETWORK  [conn2] received client metadata from 172.18.1.1:58480 conn2: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:35:23.991+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58482 #3 (3 connections now open)
2018-05-07T09:35:23.992+0000 I NETWORK  [conn3] received client metadata from 172.18.1.1:58482 conn3: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:35:24.314+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58484 #4 (4 connections now open)
2018-05-07T09:35:24.315+0000 I NETWORK  [conn4] received client metadata from 172.18.1.1:58484 conn4: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:35:24.892+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58486 #5 (5 connections now open)
2018-05-07T09:35:24.893+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58488 #6 (6 connections now open)
2018-05-07T09:35:24.893+0000 I NETWORK  [conn5] received client metadata from 172.18.1.1:58486 conn5: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:35:24.893+0000 I NETWORK  [conn6] received client metadata from 172.18.1.1:58488 conn6: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T09:36:58.028+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58500 #7 (7 connections now open)
2018-05-07T09:36:58.028+0000 I NETWORK  [conn7] received client metadata from 172.18.1.1:58500 conn7: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T09:36:58.031+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58504 #8 (8 connections now open)
2018-05-07T09:36:58.031+0000 I NETWORK  [conn8] received client metadata from 172.18.1.1:58504 conn8: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T09:36:58.044+0000 I ACCESS   [conn8] Successfully authenticated as principal penework on penework
2018-05-07T09:36:58.070+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58508 #9 (9 connections now open)
2018-05-07T09:36:58.071+0000 I NETWORK  [conn9] received client metadata from 172.18.1.1:58508 conn9: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T09:36:58.078+0000 I COMMAND  [conn8] CMD: drop penework.Projects
2018-05-07T09:37:13.654+0000 I -        [conn7] end connection 172.18.1.1:58500 (9 connections now open)
2018-05-07T09:37:13.654+0000 I -        [conn8] end connection 172.18.1.1:58504 (9 connections now open)
2018-05-07T09:37:13.670+0000 I -        [conn9] end connection 172.18.1.1:58508 (7 connections now open)
2018-05-07T10:19:22.349+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 0, after security: 0, after storageEngine: 0, after tcmalloc: 0, after wiredTiger: 1430, at end: 1430 }
2018-05-07T10:49:34.001+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 0, after security: 0, after storageEngine: 0, after tcmalloc: 1779781, after wiredTiger: 1779781, at end: 1779781 }
2018-05-07T11:46:47.962+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 0, after security: 0, after storageEngine: 0, after tcmalloc: 0, after wiredTiger: 0, at end: 1374 }
2018-05-07T11:47:41.735+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 0, after security: 0, after storageEngine: 0, after tcmalloc: 0, after wiredTiger: 1327, at end: 1327 }
2018-05-07T13:30:57.842+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58512 #10 (7 connections now open)
2018-05-07T13:30:57.843+0000 I NETWORK  [conn10] received client metadata from 172.18.1.1:58512 conn10: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:30:57.849+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58516 #11 (8 connections now open)
2018-05-07T13:30:57.849+0000 I NETWORK  [conn11] received client metadata from 172.18.1.1:58516 conn11: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:30:57.858+0000 I ACCESS   [conn11] Successfully authenticated as principal penework on penework
2018-05-07T13:30:58.426+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58520 #12 (9 connections now open)
2018-05-07T13:30:58.427+0000 I NETWORK  [conn12] received client metadata from 172.18.1.1:58520 conn12: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:30:58.439+0000 I COMMAND  [conn11] CMD: drop penework.Projects
2018-05-07T13:31:13.983+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58524 #13 (10 connections now open)
2018-05-07T13:31:13.983+0000 I NETWORK  [conn13] received client metadata from 172.18.1.1:58524 conn13: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:31:13.986+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58528 #14 (11 connections now open)
2018-05-07T13:31:13.987+0000 I NETWORK  [conn14] received client metadata from 172.18.1.1:58528 conn14: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:31:13.995+0000 I ACCESS   [conn14] Successfully authenticated as principal penework on penework
2018-05-07T13:31:14.669+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58532 #15 (12 connections now open)
2018-05-07T13:31:14.670+0000 I NETWORK  [conn15] received client metadata from 172.18.1.1:58532 conn15: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:31:14.685+0000 I COMMAND  [conn14] CMD: drop penework.Projects
2018-05-07T13:32:01.848+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58534 #16 (13 connections now open)
2018-05-07T13:32:01.849+0000 I NETWORK  [conn16] received client metadata from 172.18.1.1:58534 conn16: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.3" }, platform: "CPython 2.7.14.final.0" }
2018-05-07T13:32:01.850+0000 I ACCESS   [conn16] Unauthorized: not authorized on penework to execute command { insert: "users", ordered: true, documents: [ { username: "adminwt0f", password: "$2b$12$044d7t3tbLSz6v5uj49en.q9V.M3NfiiRU.16wv3LYKpOAusRGxIO", active: true, roles: [], _id: ObjectId('5af055d4cb2ca72b6a79148d') } ], writeConcern: { w: 1 } }
2018-05-07T13:33:05.574+0000 I -        [conn13] end connection 172.18.1.1:58524 (13 connections now open)
2018-05-07T13:33:05.574+0000 I -        [conn14] end connection 172.18.1.1:58528 (13 connections now open)
2018-05-07T13:33:05.594+0000 I -        [conn15] end connection 172.18.1.1:58532 (11 connections now open)
2018-05-07T13:33:06.033+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58540 #17 (11 connections now open)
2018-05-07T13:33:06.034+0000 I NETWORK  [conn17] received client metadata from 172.18.1.1:58540 conn17: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:06.037+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58544 #18 (12 connections now open)
2018-05-07T13:33:06.037+0000 I NETWORK  [conn18] received client metadata from 172.18.1.1:58544 conn18: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:06.046+0000 I ACCESS   [conn18] Successfully authenticated as principal penework on penework
2018-05-07T13:33:06.646+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58548 #19 (13 connections now open)
2018-05-07T13:33:06.647+0000 I NETWORK  [conn19] received client metadata from 172.18.1.1:58548 conn19: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:06.659+0000 I COMMAND  [conn18] CMD: drop penework.Projects
2018-05-07T13:33:11.901+0000 I -        [conn11] end connection 172.18.1.1:58516 (13 connections now open)
2018-05-07T13:33:11.901+0000 I -        [conn10] end connection 172.18.1.1:58512 (13 connections now open)
2018-05-07T13:33:11.917+0000 I -        [conn12] end connection 172.18.1.1:58520 (11 connections now open)
2018-05-07T13:33:12.086+0000 I -        [conn18] end connection 172.18.1.1:58544 (10 connections now open)
2018-05-07T13:33:12.086+0000 I -        [conn17] end connection 172.18.1.1:58540 (10 connections now open)
2018-05-07T13:33:12.100+0000 I -        [conn19] end connection 172.18.1.1:58548 (8 connections now open)
2018-05-07T13:33:13.114+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58552 #20 (8 connections now open)
2018-05-07T13:33:13.114+0000 I NETWORK  [conn20] received client metadata from 172.18.1.1:58552 conn20: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:13.117+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58556 #21 (9 connections now open)
2018-05-07T13:33:13.117+0000 I NETWORK  [conn21] received client metadata from 172.18.1.1:58556 conn21: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:13.126+0000 I ACCESS   [conn21] Successfully authenticated as principal penework on penework
2018-05-07T13:33:13.698+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58560 #22 (10 connections now open)
2018-05-07T13:33:13.699+0000 I NETWORK  [conn22] received client metadata from 172.18.1.1:58560 conn22: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:13.710+0000 I COMMAND  [conn21] CMD: drop penework.Projects
2018-05-07T13:33:29.274+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58574 #23 (11 connections now open)
2018-05-07T13:33:29.285+0000 I NETWORK  [conn23] received client metadata from 172.18.1.1:58574 conn23: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:29.291+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58578 #24 (12 connections now open)
2018-05-07T13:33:29.292+0000 I NETWORK  [conn24] received client metadata from 172.18.1.1:58578 conn24: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:29.302+0000 I ACCESS   [conn24] Successfully authenticated as principal penework on penework
2018-05-07T13:33:29.885+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58582 #25 (13 connections now open)
2018-05-07T13:33:29.886+0000 I NETWORK  [conn25] received client metadata from 172.18.1.1:58582 conn25: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:33:29.903+0000 I COMMAND  [conn24] CMD: drop penework.Projects
2018-05-07T13:35:16.749+0000 I -        [conn23] end connection 172.18.1.1:58574 (13 connections now open)
2018-05-07T13:35:16.749+0000 I -        [conn24] end connection 172.18.1.1:58578 (13 connections now open)
2018-05-07T13:35:16.766+0000 I -        [conn25] end connection 172.18.1.1:58582 (11 connections now open)
2018-05-07T13:35:17.387+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58588 #26 (11 connections now open)
2018-05-07T13:35:17.388+0000 I NETWORK  [conn26] received client metadata from 172.18.1.1:58588 conn26: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:35:17.394+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58592 #27 (12 connections now open)
2018-05-07T13:35:17.395+0000 I NETWORK  [conn27] received client metadata from 172.18.1.1:58592 conn27: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:35:17.404+0000 I ACCESS   [conn27] Successfully authenticated as principal penework on penework
2018-05-07T13:35:18.021+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58596 #28 (13 connections now open)
2018-05-07T13:35:18.022+0000 I NETWORK  [conn28] received client metadata from 172.18.1.1:58596 conn28: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:35:18.033+0000 I COMMAND  [conn27] CMD: drop penework.Projects
2018-05-07T13:35:23.574+0000 I -        [conn26] end connection 172.18.1.1:58588 (13 connections now open)
2018-05-07T13:35:23.575+0000 I -        [conn27] end connection 172.18.1.1:58592 (13 connections now open)
2018-05-07T13:35:23.589+0000 I -        [conn28] end connection 172.18.1.1:58596 (11 connections now open)
2018-05-07T13:35:23.629+0000 I -        [conn21] end connection 172.18.1.1:58556 (10 connections now open)
2018-05-07T13:35:23.629+0000 I -        [conn20] end connection 172.18.1.1:58552 (10 connections now open)
2018-05-07T13:35:23.647+0000 I -        [conn22] end connection 172.18.1.1:58560 (8 connections now open)
2018-05-07T13:36:30.193+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58600 #29 (8 connections now open)
2018-05-07T13:36:30.194+0000 I NETWORK  [conn29] received client metadata from 172.18.1.1:58600 conn29: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:36:30.197+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58604 #30 (9 connections now open)
2018-05-07T13:36:30.197+0000 I NETWORK  [conn30] received client metadata from 172.18.1.1:58604 conn30: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:36:30.206+0000 I ACCESS   [conn30] Successfully authenticated as principal penework on penework
2018-05-07T13:36:31.234+0000 I -        [conn29] end connection 172.18.1.1:58600 (9 connections now open)
2018-05-07T13:36:31.234+0000 I -        [conn30] end connection 172.18.1.1:58604 (9 connections now open)
2018-05-07T13:37:02.360+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58608 #31 (8 connections now open)
2018-05-07T13:37:02.360+0000 I NETWORK  [conn31] received client metadata from 172.18.1.1:58608 conn31: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:37:02.363+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58612 #32 (9 connections now open)
2018-05-07T13:37:02.363+0000 I NETWORK  [conn32] received client metadata from 172.18.1.1:58612 conn32: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:37:02.372+0000 I ACCESS   [conn32] Successfully authenticated as principal penework on penework
2018-05-07T13:37:03.429+0000 I -        [conn31] end connection 172.18.1.1:58608 (9 connections now open)
2018-05-07T13:37:03.429+0000 I -        [conn32] end connection 172.18.1.1:58612 (9 connections now open)
2018-05-07T13:38:27.284+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58616 #33 (8 connections now open)
2018-05-07T13:38:27.284+0000 I NETWORK  [conn33] received client metadata from 172.18.1.1:58616 conn33: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:27.287+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58620 #34 (9 connections now open)
2018-05-07T13:38:27.288+0000 I NETWORK  [conn34] received client metadata from 172.18.1.1:58620 conn34: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:27.297+0000 I ACCESS   [conn34] Successfully authenticated as principal penework on penework
2018-05-07T13:38:27.847+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58624 #35 (10 connections now open)
2018-05-07T13:38:27.847+0000 I NETWORK  [conn35] received client metadata from 172.18.1.1:58624 conn35: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:27.851+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58628 #36 (11 connections now open)
2018-05-07T13:38:27.851+0000 I NETWORK  [conn36] received client metadata from 172.18.1.1:58628 conn36: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:27.861+0000 I ACCESS   [conn36] Successfully authenticated as principal penework on penework
2018-05-07T13:38:28.160+0000 I COMMAND  [conn34] CMD: drop penework.Projects
2018-05-07T13:38:43.659+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58632 #37 (12 connections now open)
2018-05-07T13:38:43.660+0000 I NETWORK  [conn37] received client metadata from 172.18.1.1:58632 conn37: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:43.667+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58636 #38 (13 connections now open)
2018-05-07T13:38:43.667+0000 I NETWORK  [conn38] received client metadata from 172.18.1.1:58636 conn38: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:43.675+0000 I ACCESS   [conn38] Successfully authenticated as principal penework on penework
2018-05-07T13:38:44.227+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58640 #39 (14 connections now open)
2018-05-07T13:38:44.228+0000 I NETWORK  [conn39] received client metadata from 172.18.1.1:58640 conn39: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:44.231+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58644 #40 (15 connections now open)
2018-05-07T13:38:44.231+0000 I NETWORK  [conn40] received client metadata from 172.18.1.1:58644 conn40: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:38:44.239+0000 I ACCESS   [conn40] Successfully authenticated as principal penework on penework
2018-05-07T13:38:44.546+0000 I COMMAND  [conn38] CMD: drop penework.Projects
2018-05-07T13:39:31.887+0000 I -        [conn38] end connection 172.18.1.1:58636 (15 connections now open)
2018-05-07T13:39:31.887+0000 I -        [conn37] end connection 172.18.1.1:58632 (15 connections now open)
2018-05-07T13:39:31.904+0000 I -        [conn39] end connection 172.18.1.1:58640 (13 connections now open)
2018-05-07T13:39:31.904+0000 I -        [conn40] end connection 172.18.1.1:58644 (13 connections now open)
2018-05-07T13:39:32.899+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58650 #41 (12 connections now open)
2018-05-07T13:39:32.900+0000 I NETWORK  [conn41] received client metadata from 172.18.1.1:58650 conn41: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:39:32.903+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58654 #42 (13 connections now open)
2018-05-07T13:39:32.903+0000 I NETWORK  [conn42] received client metadata from 172.18.1.1:58654 conn42: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:39:32.912+0000 I ACCESS   [conn42] Successfully authenticated as principal penework on penework
2018-05-07T13:39:32.942+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58658 #43 (14 connections now open)
2018-05-07T13:39:32.943+0000 I NETWORK  [conn43] received client metadata from 172.18.1.1:58658 conn43: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:39:32.946+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58662 #44 (15 connections now open)
2018-05-07T13:39:32.947+0000 I NETWORK  [conn44] received client metadata from 172.18.1.1:58662 conn44: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:39:32.956+0000 I ACCESS   [conn44] Successfully authenticated as principal penework on penework
2018-05-07T13:39:33.262+0000 I COMMAND  [conn42] CMD: drop penework.Projects
2018-05-07T13:40:00.069+0000 I -        [conn42] end connection 172.18.1.1:58654 (15 connections now open)
2018-05-07T13:40:00.069+0000 I -        [conn41] end connection 172.18.1.1:58650 (15 connections now open)
2018-05-07T13:40:00.087+0000 I -        [conn43] end connection 172.18.1.1:58658 (13 connections now open)
2018-05-07T13:40:00.087+0000 I -        [conn44] end connection 172.18.1.1:58662 (12 connections now open)
2018-05-07T13:40:01.149+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58668 #45 (12 connections now open)
2018-05-07T13:40:01.149+0000 I NETWORK  [conn45] received client metadata from 172.18.1.1:58668 conn45: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:01.153+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58672 #46 (13 connections now open)
2018-05-07T13:40:01.153+0000 I NETWORK  [conn46] received client metadata from 172.18.1.1:58672 conn46: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:01.164+0000 I ACCESS   [conn46] Successfully authenticated as principal penework on penework
2018-05-07T13:40:01.196+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58676 #47 (14 connections now open)
2018-05-07T13:40:01.197+0000 I NETWORK  [conn47] received client metadata from 172.18.1.1:58676 conn47: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:01.199+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58680 #48 (15 connections now open)
2018-05-07T13:40:01.200+0000 I NETWORK  [conn48] received client metadata from 172.18.1.1:58680 conn48: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:01.211+0000 I ACCESS   [conn48] Successfully authenticated as principal penework on penework
2018-05-07T13:40:01.507+0000 I COMMAND  [conn46] CMD: drop penework.Projects
2018-05-07T13:40:31.309+0000 I -        [conn45] end connection 172.18.1.1:58668 (15 connections now open)
2018-05-07T13:40:31.309+0000 I -        [conn46] end connection 172.18.1.1:58672 (15 connections now open)
2018-05-07T13:40:31.327+0000 I -        [conn47] end connection 172.18.1.1:58676 (13 connections now open)
2018-05-07T13:40:31.327+0000 I -        [conn48] end connection 172.18.1.1:58680 (13 connections now open)
2018-05-07T13:40:32.338+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58684 #49 (12 connections now open)
2018-05-07T13:40:32.338+0000 I NETWORK  [conn49] received client metadata from 172.18.1.1:58684 conn49: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:32.341+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58688 #50 (13 connections now open)
2018-05-07T13:40:32.342+0000 I NETWORK  [conn50] received client metadata from 172.18.1.1:58688 conn50: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:32.350+0000 I ACCESS   [conn50] Successfully authenticated as principal penework on penework
2018-05-07T13:40:32.385+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58692 #51 (14 connections now open)
2018-05-07T13:40:32.386+0000 I NETWORK  [conn51] received client metadata from 172.18.1.1:58692 conn51: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:32.389+0000 I NETWORK  [thread1] connection accepted from 172.18.1.1:58696 #52 (15 connections now open)
2018-05-07T13:40:32.389+0000 I NETWORK  [conn52] received client metadata from 172.18.1.1:58696 conn52: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "debian 8.10", architecture: "x86_64", version: "4.9.60-linuxkit-aufs" }, platform: "CPython 2.7.9.final.0" }
2018-05-07T13:40:32.399+0000 I ACCESS   [conn52] Successfully authenticated as principal penework on penework
2018-05-07T13:40:32.708+0000 I COMMAND  [conn50] CMD: drop penework.Projects
2018-05-07T13:40:41.442+0000 I -        [conn50] end connection 172.18.1.1:58688 (15 connections now open)
2018-05-07T13:40:41.442+0000 I -        [conn49] end connection 172.18.1.1:58684 (15 connections now open)
2018-05-07T13:40:41.457+0000 I -        [conn52] end connection 172.18.1.1:58696 (13 connections now open)
2018-05-07T13:40:41.457+0000 I -        [conn51] end connection 172.18.1.1:58692 (13 connections now open)
2018-05-07T13:40:41.758+0000 I -        [conn33] end connection 172.18.1.1:58616 (11 connections now open)
2018-05-07T13:40:41.759+0000 I -        [conn34] end connection 172.18.1.1:58620 (11 connections now open)
2018-05-07T13:40:41.776+0000 I -        [conn36] end connection 172.18.1.1:58628 (9 connections now open)
2018-05-07T13:40:41.777+0000 I -        [conn35] end connection 172.18.1.1:58624 (9 connections now open)
